"""add description to products

Revision ID: 012ea6f228cc
Revises: 4c96a7b2c0ea
Create Date: 2020-01-23 15:21:38.126494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012ea6f228cc'
down_revision = '4c96a7b2c0ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
